services:
  db:
    platform: linux/amd64
    image: postgres:16-alpine # Use a specific version of Postgres
    restart: always
    ports:
      - '5432:5432' # Expose the Postgres port to your local machine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - subscription_management:/var/lib/postgresql/data

volumes:
  subscription_management: