packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: false
  prisma: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.16'
  - '@turbo/darwin-arm64@2.9.16'
  - '@turbo/linux-64@2.9.16'
  - '@turbo/linux-arm64@2.9.16'
  - '@turbo/windows-64@2.9.16'
  - '@turbo/windows-arm64@2.9.16'
  - turbo@2.9.16
